### ISSUE TITLE
Undo does not work

### ISSUE THREAD

**Issue by Lukasfuh** [crashcloud/Crash#25]
**Describe the bug**
Have 2 instances join a server. Make a box, move it and then undo then move it. The instance that does not own the box will see it in the original position.

**To Reproduce**
1. Join model
2. Make Box
3. Move
4. Undo

**Expected behavior**

**Screenshots**

**Version Info (please complete the following information):**
 - Rhino Version [x.x.x]
 - Crash Version [x.x.x]

**Additional context**

**Comment by clicketyclackety** [comment]
Resolved by #38
